#!/bin/bash

if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    echo "This script is meant to set some environment variables, so you"\
        "have to source it instead of executing it directly."
    exit 1
fi

export PATH="$(npm bin):$PATH"
